import Head from "next/head";
import styles from "../styles/Home.module.css";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="keywords" content="next,next Blog, hunting coder" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className=" py-3 m-auto w-2/4">
    <img className="rounded-md" alt="coder" src="/homeImg.jpg" width={507} height={339}/>
    </div>
    </div>
  );
}
